---
- name: Create directory for custom footer
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "u=rwX,g=rX,o="
  loop:
    - "{{ gitea_custom }}/templates"
    - "{{ gitea_custom }}/templates/custom"

- name: Transfer custom footer template
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_footer) }}"
    dest: "{{ gitea_custom }}/templates/custom/extra_links_footer.tmpl"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  failed_when: false
  tags: skip_ansible_lint
  notify: "systemctl restart gitea"
