---
- name: Create directory for custom logos
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"
  loop:
    - "{{ gitea_custom }}/public"
    - "{{ gitea_custom }}/public/assets"
    - "{{ gitea_custom }}/public/assets/img"

- name: Transfer custom logo.svg
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_logosvg) }}"
    dest: "{{ gitea_custom }}/public/assets/img/logo.svg"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  tags: skip_ansible_lint
  failed_when: false

- name: Transfer custom logo.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_logopng) }}"
    dest: "{{ gitea_custom }}/public/assets/img/logo.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  tags: skip_ansible_lint
  failed_when: false

- name: Transfer custom favicon.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_faviconpng) }}"
    dest: "{{ gitea_custom }}/public/assets/img/favicon.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  tags: skip_ansible_lint
  failed_when: false

- name: Transfer custom favicon.svg
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_faviconsvg) }}"
    dest: "{{ gitea_custom }}/public/assets/img/favicon.svg"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  tags: skip_ansible_lint
  failed_when: false

- name: Transfer custom apple-touch-icon.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_appletouchiconpng) }}"
    dest: "{{ gitea_custom }}/public/assets/img/apple-touch-icon.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0640"
  tags: skip_ansible_lint
  failed_when: false
