---
- name: "Setup systemd service"
  become: true
  ansible.builtin.template:
    src: "templates/gitea.service.j2"
    dest: "{{ gitea_systemd_path }}/gitea.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "Reload systemd"
    - "systemctl restart gitea"

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
